export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  ON_MARKET = 'ON_MARKET',
  PASSED = 'PASSED',
  PRINTED = 'PRINTED',
  TRANSFERRED = 'TRANSFERRED'
}
